# Generated by Django 4.1 on 2024-04-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_predresults_chlorides'),
    ]

    operations = [
        migrations.AddField(
            model_name='predresults',
            name='alcohol',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predresults',
            name='density',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predresults',
            name='free_sulfur_dioxide',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predresults',
            name='pH',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predresults',
            name='sulphates',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predresults',
            name='total_sulfur_dioxide',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
